-- supabase/migrations/032_bible_books.sql
-- Book-level study apparatus (~66 curated rows). Public read (reference data,
-- not user-scoped). Keyed by `book` to match bible_passages.book (lowercase OSIS).
-- Authorship uncertainty is a first-class column so the rail can show it honestly.

create table public.bible_books (
  book text primary key,                  -- lowercase OSIS, matches bible_passages.book
  canonical_order integer not null,
  testament text not null check (testament in ('OT', 'NT')),
  full_name text not null,
  author text not null,
  author_note text not null default '',   -- e.g. "traditionally attributed to Moses; authorship debated"
  date_label text not null default '',    -- e.g. "~57 AD"
  date_start_year integer,                -- negative = BC; for same-era queries
  date_end_year integer,
  region text not null default '',
  provenance_note text not null default '',
  cultural_context text not null default '',
  genre text not null default '',
  summary text not null default '',
  source text not null default '',
  source_url text not null default ''
);

create index bible_books_author on public.bible_books (author);
create index bible_books_date_range on public.bible_books (date_start_year, date_end_year);

alter table public.bible_books enable row level security;

create policy "Anyone can read bible_books"
  on public.bible_books for select using (true);

insert into public.bible_books
  (book, canonical_order, testament, full_name, author, author_note, date_label, date_start_year, date_end_year, region, provenance_note, cultural_context, genre, summary, source, source_url)
values
  ('gen', 1, 'OT', 'Genesis', 'Moses (traditional)', 'Traditionally attributed to Moses; modern scholarship identifies composite sources (J, E, D, P).', '~1446–1406 BC (traditional)', -1446, -1406, 'Ancient Near East', 'Pentateuch; date and authorship widely debated.', 'Patriarchal and ancient Near Eastern cultural setting.', 'Narrative / Law', 'Origins of the cosmos, humanity, sin, and the covenant family of Abraham, Isaac, and Jacob.', 'In-house, public-domain references', ''),
  ('exo', 2, 'OT', 'Exodus', 'Moses (traditional)', 'Traditionally attributed to Moses; authorship and date contested among scholars.', '~1446–1406 BC (traditional)', -1446, -1406, 'Egypt / Sinai', 'Pentateuch.', 'Israel''s bondage in Egypt and the Mosaic covenant at Sinai.', 'Narrative / Law', 'Deliverance of Israel from Egypt, the plagues, the Passover, and the giving of the Law at Sinai.', 'In-house, public-domain references', ''),
  ('lev', 3, 'OT', 'Leviticus', 'Moses (traditional)', 'Traditionally attributed to Moses; part of the Priestly source in modern source criticism.', '~1446–1406 BC (traditional)', -1446, -1406, 'Sinai', 'Pentateuch; legislative-priestly material.', 'Priestly law governing Israel''s worship and holiness.', 'Law / Ritual', 'Regulations for sacrifice, purity, priesthood, and the holiness of the covenant community.', 'In-house, public-domain references', ''),
  ('num', 4, 'OT', 'Numbers', 'Moses (traditional)', 'Traditionally attributed to Moses; composite sources evident in modern scholarship.', '~1446–1406 BC (traditional)', -1446, -1406, 'Sinai / Wilderness', 'Pentateuch.', 'Israel''s wilderness wandering and the transition to the Promised Land generation.', 'Narrative / Law', 'Israel''s census, wilderness journey, rebellions, and preparations for entering Canaan.', 'In-house, public-domain references', ''),
  ('deu', 5, 'OT', 'Deuteronomy', 'Moses (traditional)', 'Traditionally the farewell speeches of Moses; scholars widely associate it with the 7th-century Deuteronomistic reform.', '~1406 BC (traditional)', -1406, -1406, 'Plains of Moab', 'Pentateuch; Deuteronomistic tradition.', 'Covenant renewal on the eve of Canaan conquest.', 'Law / Sermon', 'Moses'' final addresses to Israel, restating the covenant and calling the nation to faithfulness before his death.', 'In-house, public-domain references', ''),
  ('jos', 6, 'OT', 'Joshua', 'Joshua (partial, traditional)', 'Traditionally associated with Joshua; modern scholarship places it in the Deuteronomistic History.', '~1400–1380 BC (traditional)', -1400, -1380, 'Canaan', 'Deuteronomistic History.', 'The Israelite conquest and settlement of Canaan.', 'Narrative', 'Israel''s conquest of Canaan under Joshua and the division of the land among the tribes.', 'In-house, public-domain references', ''),
  ('jdg', 7, 'OT', 'Judges', 'Unknown (Deuteronomistic)', 'Authorship unknown; part of the Deuteronomistic History; final form likely 6th century BC.', '~1380–1050 BC (events)', -1380, -1050, 'Canaan', 'Deuteronomistic History.', 'Cyclical patterns of apostasy and deliverance in pre-monarchic Israel.', 'Narrative', 'The era of tribal judges who delivered Israel from oppression during cycles of sin and repentance.', 'In-house, public-domain references', ''),
  ('rut', 8, 'OT', 'Ruth', 'Unknown', 'Authorship unknown; date of composition debated (pre-exilic to post-exilic range).', '~1100–1000 BC (events)', -1100, -1000, 'Moab / Bethlehem', 'Date uncertain; perhaps composed during or after the monarchy.', 'Loyalty, redemption, and the inclusion of a Gentile in Israel''s covenant community.', 'Narrative', 'The story of Ruth''s faithfulness to Naomi and her marriage to Boaz, ancestor of David.', 'In-house, public-domain references', ''),
  ('1sa', 9, 'OT', '1 Samuel', 'Unknown (Deuteronomistic)', 'Authorship unknown; traditionally associated with Samuel, Nathan, and Gad; part of the Deuteronomistic History.', '~1050–970 BC (events)', -1050, -970, 'Canaan', 'Deuteronomistic History.', 'The transition from judges to monarchy in Israel.', 'Narrative', 'Samuel''s ministry, Saul''s reign, and the rise of David as the chosen king.', 'In-house, public-domain references', ''),
  ('2sa', 10, 'OT', '2 Samuel', 'Unknown (Deuteronomistic)', 'Continuation of 1 Samuel; part of the Deuteronomistic History; authorship unknown.', '~1010–970 BC (events)', -1010, -970, 'Judah / Israel', 'Deuteronomistic History.', 'David''s reign as king over all Israel.', 'Narrative', 'David''s reign: his military victories, personal sins, and the consequences for his dynasty.', 'In-house, public-domain references', ''),
  ('1ki', 11, 'OT', '1 Kings', 'Unknown (Deuteronomistic)', 'Authorship unknown; part of the Deuteronomistic History; compiled and edited during or after the Babylonian exile.', '~970–853 BC (events)', -970, -853, 'Judah / Israel', 'Deuteronomistic History.', 'The height of the monarchy under Solomon and the division into two kingdoms.', 'Narrative', 'Solomon''s reign, the building of the Temple, the kingdom''s division, and the ministry of Elijah.', 'In-house, public-domain references', ''),
  ('2ki', 12, 'OT', '2 Kings', 'Unknown (Deuteronomistic)', 'Continuation of 1 Kings; Deuteronomistic History; authorship unknown.', '~853–586 BC (events)', -853, -586, 'Judah / Israel', 'Deuteronomistic History.', 'The declining years of divided monarchy leading to Assyrian and Babylonian exile.', 'Narrative', 'The ministry of Elisha, the fall of the northern kingdom to Assyria, and the fall of Jerusalem to Babylon.', 'In-house, public-domain references', ''),
  ('1ch', 13, 'OT', '1 Chronicles', 'Ezra (traditional)', 'Traditionally attributed to Ezra; scholarly opinion varies; likely post-exilic composition.', '~450–400 BC (composition)', -450, -400, 'Post-exilic Judah', 'Post-exilic; possibly related to Ezra-Nehemiah.', 'Restoration-era retelling of Israel''s history emphasizing the Davidic covenant and temple worship.', 'Narrative / Genealogy', 'Genealogies from Adam to David, and David''s preparation for temple worship.', 'In-house, public-domain references', ''),
  ('2ch', 14, 'OT', '2 Chronicles', 'Ezra (traditional)', 'Traditionally attributed to Ezra; likely post-exilic; parallels and supplements Kings with a temple-focused perspective.', '~450–400 BC (composition)', -450, -400, 'Post-exilic Judah', 'Post-exilic; possibly related to Ezra-Nehemiah.', 'Restoration emphasis on Davidic kingship and Levitical worship.', 'Narrative', 'Solomon''s reign, the temple, the divided kingdom through the fall of Jerusalem, and Cyrus'' decree.', 'In-house, public-domain references', ''),
  ('ezr', 15, 'OT', 'Ezra', 'Ezra (traditional)', 'Traditionally attributed to Ezra the scribe; some scholars combine Ezra-Nehemiah as one work.', '~450 BC', -450, -430, 'Post-exilic Judah / Persia', 'Post-exilic return under Persian rule.', 'Return from Babylonian exile and re-establishment of Jewish worship.', 'Narrative', 'The return of Jewish exiles from Babylon, the rebuilding of the temple, and Ezra''s reforms.', 'In-house, public-domain references', ''),
  ('neh', 16, 'OT', 'Nehemiah', 'Nehemiah (traditional)', 'Contains first-person memoirs attributed to Nehemiah; possibly edited together with Ezra.', '~445–430 BC', -445, -430, 'Post-exilic Jerusalem', 'Post-exilic; Persian period.', 'Rebuilding of Jerusalem''s walls and social-religious reform.', 'Narrative / Memoir', 'Nehemiah''s leadership in rebuilding Jerusalem''s walls and instituting covenant renewal.', 'In-house, public-domain references', ''),
  ('est', 17, 'OT', 'Esther', 'Unknown', 'Authorship unknown; date of composition debated (Persian-period to Maccabean range).', '~480 BC (events)', -483, -473, 'Persia', 'Diaspora setting; authorship and date uncertain.', 'Jewish life under Persian rule; identity and survival in the diaspora.', 'Narrative', 'Esther''s courage in saving the Jewish people from Haman''s genocidal plot at the Persian court.', 'In-house, public-domain references', ''),
  ('job', 18, 'OT', 'Job', 'Unknown', 'Authorship unknown and date highly uncertain; wisdom tradition; the story may predate its written form.', 'Date uncertain', null, null, 'Unknown / Ancient Near East', 'Wisdom literature; no secure date for composition.', 'The problem of innocent suffering and the limits of human wisdom.', 'Wisdom / Poetry', 'Job''s suffering, the debate between Job and his friends, and God''s answer from the whirlwind.', 'In-house, public-domain references', ''),
  ('psa', 19, 'OT', 'Psalms', 'Multiple authors', 'Attributed to David (73 psalms), Asaph, the sons of Korah, Solomon, Moses, and others; compiled over many centuries.', '~1000–400 BC', -1000, -400, 'Israel', 'Compiled hymnbook of the Second Temple; diverse authorship and dates.', 'Israel''s worship, lament, praise, and meditation on Torah.', 'Poetry / Hymn / Lament', 'A collection of 150 poems and hymns expressing the full range of human experience before God.', 'In-house, public-domain references', ''),
  ('pro', 20, 'OT', 'Proverbs', 'Solomon (primary tradition)', 'Attributed primarily to Solomon (1:1, 10:1, 25:1); also Agur (30:1) and Lemuel (31:1); compiled over centuries.', '~950–700 BC (core); compiled later', -950, -700, 'Israel', 'Wisdom tradition; composite compilation.', 'Practical wisdom for daily life rooted in fear of the Lord.', 'Wisdom / Poetry', 'Collected sayings and discourses on wisdom, virtue, folly, and the good life.', 'In-house, public-domain references', ''),
  ('ecc', 21, 'OT', 'Ecclesiastes', 'Qohelet (traditional: Solomon)', 'The author calls himself "Qohelet" (the Preacher/Teacher); traditionally identified as Solomon, though the Hebrew suggests a later date.', '~450–200 BC (composition likely post-exilic)', -450, -200, 'Jerusalem (likely)', 'Wisdom literature; date and authorship debated.', 'Reflection on the limits of human wisdom, wealth, and labor.', 'Wisdom / Philosophy', 'A meditation on the vanity of human striving and the importance of fearing God amid life''s uncertainties.', 'In-house, public-domain references', ''),
  ('sng', 22, 'OT', 'Song of Solomon', 'Solomon (traditional)', 'Traditionally attributed to Solomon; modern scholarship notes the language suggests a later date; authorship debated.', '~950 BC (traditional)', -950, -950, 'Israel', 'Wisdom tradition; authorship and date uncertain.', 'Love, desire, and relationship expressed through rich poetic imagery.', 'Poetry / Love Song', 'A collection of love poems celebrating human love, interpreted by many as an allegory of God''s love for Israel.', 'In-house, public-domain references', ''),
  ('isa', 23, 'OT', 'Isaiah', 'Isaiah ben Amoz (chapters 1–39 core)', 'Chapters 1–39 associated with Isaiah of Jerusalem (8th century BC); chapters 40–55 and 56–66 widely attributed to later authors by modern scholars (Deutero- and Trito-Isaiah).', '~740–700 BC (Isa 1–39); ~550–520 BC (Isa 40–55)', -740, -520, 'Judah / Babylon', 'Prophetic book; composite authorship debated.', 'Judgment on Israel and the nations; eschatological hope; Servant Songs.', 'Prophecy / Poetry', 'Oracles of judgment and hope spanning the Assyrian crisis and the anticipated Babylonian exile and restoration.', 'In-house, public-domain references', ''),
  ('jer', 24, 'OT', 'Jeremiah', 'Jeremiah (with Baruch)', 'Attributed to Jeremiah the prophet; Baruch ben Neriah is identified as his scribe; editorial shaping over time.', '~627–586 BC', -627, -586, 'Judah / Egypt', 'Prophetic book; complex editorial history.', 'Covenant faithlessness, impending judgment, and the promise of a new covenant.', 'Prophecy / Lament', 'Jeremiah''s ministry through the fall of Jerusalem: calls to repentance, laments, and the new covenant promise.', 'In-house, public-domain references', ''),
  ('lam', 25, 'OT', 'Lamentations', 'Jeremiah (traditional)', 'Traditionally attributed to Jeremiah; many modern scholars treat it as anonymous; composed shortly after Jerusalem''s fall.', '~586 BC', -586, -580, 'Judah / Babylon', 'Composed after the fall of Jerusalem (587/586 BC).', 'Communal grief over the destruction of Jerusalem and the temple.', 'Poetry / Lament', 'Five acrostic poems mourning the destruction of Jerusalem and crying out to God for mercy and restoration.', 'In-house, public-domain references', ''),
  ('ezk', 26, 'OT', 'Ezekiel', 'Ezekiel', 'Attributed to the prophet Ezekiel; generally accepted as substantially his work; composed during the Babylonian exile.', '~593–573 BC', -593, -573, 'Babylon (exile)', 'Prophetic book; Babylonian exile setting.', 'Judgment on Israel and the nations; vision of the restored temple and new covenant.', 'Prophecy / Vision', 'Ezekiel''s visions, symbolic acts, oracles of judgment on Israel and the nations, and the vision of the restored land.', 'In-house, public-domain references', ''),
  ('dan', 27, 'OT', 'Daniel', 'Daniel (traditional)', 'Traditionally attributed to Daniel in the 6th century BC; most modern scholars date the final form to the 2nd century BC (Maccabean period).', '~165 BC (final form, likely)', -600, -165, 'Babylon / Persia (setting)', 'Authorship and date significantly debated; apocalyptic genre.', 'Faithfulness under foreign domination; apocalyptic visions of the end of ages.', 'Narrative / Apocalyptic', 'Daniel''s faithfulness at the Babylonian court and his visions of world kingdoms and the coming kingdom of God.', 'In-house, public-domain references', ''),
  ('hos', 28, 'OT', 'Hosea', 'Hosea', 'Attributed to Hosea the prophet; composed in the northern kingdom of Israel in the 8th century BC.', '~755–722 BC', -755, -722, 'Northern Kingdom of Israel', 'Minor prophet; pre-fall of Samaria.', 'Covenant unfaithfulness compared to marital infidelity; God''s enduring love.', 'Prophecy', 'Hosea''s marriage as a metaphor for Israel''s spiritual adultery, and God''s relentless love despite unfaithfulness.', 'In-house, public-domain references', ''),
  ('jol', 29, 'OT', 'Joel', 'Joel', 'Attributed to Joel son of Pethuel; date highly debated (pre-exilic to post-exilic range).', 'Date uncertain (possibly ~400 BC)', null, null, 'Judah', 'Date and background uncertain; post-exilic setting likely.', 'Locust plague as harbinger of the Day of the Lord; future outpouring of the Spirit.', 'Prophecy', 'A locust plague interpreted as judgment, calling to repentance, and the promise of the Spirit on all flesh.', 'In-house, public-domain references', ''),
  ('amo', 30, 'OT', 'Amos', 'Amos', 'Attributed to Amos of Tekoa, a herdsman-prophet; composed in the 8th century BC.', '~760–750 BC', -760, -750, 'Israel (north)', 'Minor prophet; 8th-century Israel.', 'Social justice, covenant faithfulness, and judgment on Israel''s complacent elite.', 'Prophecy', 'Amos'' oracles against the nations and Israel, condemning injustice and empty religious observance.', 'In-house, public-domain references', ''),
  ('oba', 31, 'OT', 'Obadiah', 'Obadiah', 'Attributed to Obadiah; the shortest OT book; date debated (post-587 BC likely).', '~586–500 BC', -586, -500, 'Edom / Judah', 'Post-fall of Jerusalem setting probable.', 'Edom''s betrayal of Judah and the coming Day of the Lord.', 'Prophecy', 'A brief oracle condemning Edom for its treachery against Judah and announcing its judgment.', 'In-house, public-domain references', ''),
  ('jon', 32, 'OT', 'Jonah', 'Unknown (story about Jonah)', 'The protagonist is Jonah son of Amittai (cf. 2 Kings 14:25); the author is unknown; date debated (8th century to post-exilic).', 'Date uncertain', null, null, 'Nineveh / Mediterranean', 'Date uncertain; possibly post-exilic.', 'God''s concern for all peoples, even Israel''s enemies; repentance and divine mercy.', 'Narrative / Parable', 'The story of Jonah''s flight from God, his time in the fish, his mission to Nineveh, and God''s rebuke of his narrow mercy.', 'In-house, public-domain references', ''),
  ('mic', 33, 'OT', 'Micah', 'Micah', 'Attributed to Micah of Moresheth, a contemporary of Isaiah; some later sections may be from editors.', '~737–698 BC', -737, -698, 'Judah', 'Minor prophet; Assyrian-era Judah.', 'Social justice, corrupt leadership, and the hope of a messianic ruler from Bethlehem.', 'Prophecy', 'Oracles of judgment on Israel''s corrupt leaders and the promise of a future shepherd-king from Bethlehem.', 'In-house, public-domain references', ''),
  ('nam', 34, 'OT', 'Nahum', 'Nahum', 'Attributed to Nahum the Elkoshite; date generally placed before Nineveh''s fall in 612 BC.', '~650–612 BC', -650, -612, 'Judah', 'Minor prophet; late Assyrian period.', 'The fall of Nineveh as judgment for Assyrian cruelty.', 'Prophecy', 'A poetic oracle announcing the imminent destruction of Nineveh, the cruel Assyrian capital.', 'In-house, public-domain references', ''),
  ('hab', 35, 'OT', 'Habakkuk', 'Habakkuk', 'Attributed to Habakkuk; date probably late 7th century BC, around the rise of Babylon.', '~612–598 BC', -612, -598, 'Judah', 'Minor prophet; Babylonian rise.', 'Wrestling with God over evil and injustice; trust in God''s sovereign plan.', 'Prophecy / Dialogue', 'A dialogue with God about why wickedness is unpunished, answered by the vision that "the righteous shall live by faith."', 'In-house, public-domain references', ''),
  ('zep', 36, 'OT', 'Zephaniah', 'Zephaniah', 'Attributed to Zephaniah; dates to the reign of Josiah, late 7th century BC.', '~640–609 BC', -640, -609, 'Judah', 'Minor prophet; Josianic reform era.', 'The coming Day of the Lord in judgment and restoration.', 'Prophecy', 'Oracles of coming judgment on Judah and the nations, ending with a promise of restoration and joy.', 'In-house, public-domain references', ''),
  ('hag', 37, 'OT', 'Haggai', 'Haggai', 'Attributed to Haggai; precisely dated to 520 BC (Darius I, year 2).', '~520 BC', -520, -520, 'Post-exilic Jerusalem', 'Minor prophet; post-exilic restoration.', 'Rebuilding the temple as covenant priority for the returning community.', 'Prophecy', 'Haggai''s calls to rebuild the Jerusalem temple and the promise of future glory greater than Solomon''s.', 'In-house, public-domain references', ''),
  ('zec', 38, 'OT', 'Zechariah', 'Zechariah (chapters 1–8 core)', 'Chapters 1–8 attributed to Zechariah ben Berechiah (520–518 BC); chapters 9–14 widely regarded as later additions by modern scholars.', '~520–518 BC (Zech 1–8); date uncertain (9–14)', -520, -400, 'Post-exilic Jerusalem', 'Minor prophet; composite authorship debated for chapters 9–14.', 'Visions of restoration and the coming messianic king; eschatological hope.', 'Prophecy / Apocalyptic', 'Night visions of Jerusalem''s restoration, the messianic king, and eschatological triumph.', 'In-house, public-domain references', ''),
  ('mal', 39, 'OT', 'Malachi', 'Malachi (or anonymous)', '"Malachi" may be a title meaning "my messenger" rather than a proper name; date probably 5th century BC.', '~450 BC', -450, -430, 'Post-exilic Judah', 'Minor prophet; post-exilic; possibly anonymous.', 'Covenant faithlessness, corrupt priesthood, and the coming messenger who prepares the Lord''s way.', 'Prophecy', 'Disputations about priestly corruption and covenant unfaithfulness, ending with the promise of Elijah before the great Day.', 'In-house, public-domain references', ''),
  ('mat', 40, 'NT', 'Matthew', 'Matthew (traditional)', 'Traditionally attributed to Matthew the apostle; most modern scholars view it as anonymous, written ~80–90 AD.', '~80–90 AD', 80, 90, 'Syria / Palestine (likely)', 'Gospel; anonymous in final form; tradition assigns it to Matthew.', 'Jesus as the fulfillment of Israel''s Scripture and the new Moses; the Kingdom of Heaven.', 'Gospel / Narrative', 'Jesus'' birth, ministry, teaching (Sermon on the Mount), death, and resurrection presented to a Jewish-Christian audience.', 'In-house, public-domain references', ''),
  ('mrk', 41, 'NT', 'Mark', 'Mark (traditional)', 'Traditionally attributed to John Mark, associate of Peter; most scholars date it ~65–70 AD; earliest of the four Gospels.', '~65–70 AD', 65, 70, 'Rome (likely)', 'Gospel; earliest canonical Gospel; anonymous in text.', 'Urgent, action-focused account of Jesus'' ministry, suffering, and death.', 'Gospel / Narrative', 'The shortest Gospel, emphasizing Jesus'' deeds, his messianic secret, and the path of discipleship through the cross.', 'In-house, public-domain references', ''),
  ('luk', 42, 'NT', 'Luke', 'Luke (traditional)', 'Traditionally attributed to Luke the physician, companion of Paul; written as first of a two-volume work with Acts.', '~80–90 AD', 80, 90, 'Unknown (possibly Greece)', 'Gospel; companion to Acts; anonymous in text, tradition assigns to Luke.', 'Jesus'' ministry to the marginalized; the universal scope of salvation.', 'Gospel / Narrative', 'A carefully researched account of Jesus'' life emphasizing prayer, the Holy Spirit, women, and the poor.', 'In-house, public-domain references', ''),
  ('jhn', 43, 'NT', 'John', 'John (traditional)', 'Traditionally attributed to John son of Zebedee; many scholars identify a "Johannine community" and a final redactor; date ~90–100 AD.', '~90–100 AD', 90, 100, 'Ephesus (likely)', 'Gospel; distinctive theology; anonymous in text.', 'High Christology: Jesus as the eternal Word, Son of God, the Way, Truth, and Life.', 'Gospel / Theological Narrative', 'Signs, discourses, and the passion narrative revealing Jesus as the incarnate Word who gives eternal life.', 'In-house, public-domain references', ''),
  ('act', 44, 'NT', 'Acts', 'Luke (traditional)', 'Traditionally attributed to Luke; companion volume to Luke''s Gospel; written ~80–90 AD.', '~80–90 AD', 80, 90, 'Unknown', 'Acts of the Apostles; second volume of Luke-Acts.', 'The spread of the gospel from Jerusalem to Rome through the Holy Spirit.', 'Narrative / History', 'The apostolic mission from Pentecost to Paul''s arrival in Rome, tracing the gospel''s expansion through the Spirit.', 'In-house, public-domain references', ''),
  ('rom', 45, 'NT', 'Romans', 'Paul', 'Attributed to Paul the apostle; widely accepted as authentic; written from Corinth ~56–57 AD.', '~56–57 AD', 56, 57, 'Corinth', 'Pauline epistle; most systematic of Paul''s letters.', 'Justification by faith, the gospel for Jew and Gentile, and the ethics of the transformed life.', 'Epistle / Theology', 'Paul''s comprehensive exposition of the gospel: sin, justification by faith, life in the Spirit, and the destiny of Israel.', 'In-house, public-domain references', ''),
  ('1co', 46, 'NT', '1 Corinthians', 'Paul', 'Attributed to Paul the apostle; widely accepted as authentic; written ~53–54 AD.', '~53–54 AD', 53, 54, 'Ephesus', 'Pauline epistle; addressed to a divided, gifted, and troubled church.', 'Church unity, sexual ethics, spiritual gifts, the resurrection, and the centrality of love.', 'Epistle', 'Paul''s responses to divisions and questions in the Corinthian church, climaxing in the resurrection chapter.', 'In-house, public-domain references', ''),
  ('2co', 47, 'NT', '2 Corinthians', 'Paul', 'Attributed to Paul; widely accepted as authentic; possibly a composite of multiple letters.', '~55–56 AD', 55, 56, 'Macedonia', 'Pauline epistle; deeply personal and defensive.', 'Apostolic suffering, weakness, and the "treasure in jars of clay."', 'Epistle', 'Paul defends his apostolic ministry, celebrates reconciliation with the Corinthians, and urges generous giving.', 'In-house, public-domain references', ''),
  ('gal', 48, 'NT', 'Galatians', 'Paul', 'Attributed to Paul; widely accepted as authentic; written ~48–55 AD (date disputed between north and south Galatian theories).', '~48–55 AD', 48, 55, 'Unknown (written to Galatian churches)', 'Pauline epistle; polemical against circumcision requirement.', 'Justification by faith alone; freedom in Christ from the works of the law.', 'Epistle', 'Paul''s vigorous defense of the gospel of grace against those requiring circumcision for Gentile believers.', 'In-house, public-domain references', ''),
  ('eph', 49, 'NT', 'Ephesians', 'Paul (disputed)', 'Attributed to Paul; authenticity disputed; many scholars consider it deutero-Pauline (~80–90 AD); others accept it as authentic (~60–62 AD).', '~60–90 AD', 60, 90, 'Rome (prison) / Unknown', 'Pauline or deutero-Pauline epistle; authorship debated.', 'The church as the body of Christ; spiritual warfare; household codes.', 'Epistle / Theology', 'A doxological letter celebrating God''s cosmic purpose in Christ and calling the church to unity and holiness.', 'In-house, public-domain references', ''),
  ('php', 50, 'NT', 'Philippians', 'Paul', 'Attributed to Paul; widely accepted as authentic; written from prison ~61–62 AD (or possibly Ephesus ~54–55 AD).', '~54–62 AD', 54, 62, 'Rome or Ephesus (prison)', 'Pauline epistle; letter of joy from prison.', 'Joy, humility, the mind of Christ, and contentment in all circumstances.', 'Epistle', 'A warm letter of gratitude and encouragement featuring the Christ-hymn and the call to rejoice in the Lord always.', 'In-house, public-domain references', ''),
  ('col', 51, 'NT', 'Colossians', 'Paul (disputed)', 'Attributed to Paul; authenticity disputed; possibly deutero-Pauline; written from prison ~60–62 AD or later.', '~60–90 AD', 60, 90, 'Rome (prison) / Unknown', 'Pauline or deutero-Pauline epistle; authorship debated.', 'The supremacy of Christ over all cosmic powers and philosophical speculation.', 'Epistle / Theology', 'Paul (or a Pauline disciple) counters proto-Gnostic teaching by affirming the all-sufficient supremacy of Christ.', 'In-house, public-domain references', ''),
  ('1th', 52, 'NT', '1 Thessalonians', 'Paul', 'Attributed to Paul; generally considered the earliest of Paul''s extant letters (~50–51 AD).', '~50–51 AD', 50, 51, 'Corinth', 'Pauline epistle; possibly the earliest NT letter.', 'Encouragement of a young church; the resurrection hope and the Day of the Lord.', 'Epistle', 'Paul''s encouragement to the persecuted Thessalonian church and instruction about the resurrection and the Lord''s return.', 'In-house, public-domain references', ''),
  ('2th', 53, 'NT', '2 Thessalonians', 'Paul (disputed)', 'Attributed to Paul; authenticity disputed; possibly deutero-Pauline; addresses eschatological confusion.', '~50–90 AD', 50, 90, 'Corinth or later', 'Pauline or deutero-Pauline epistle; authorship debated.', 'Clarification of the Day of the Lord and call to steadfastness under persecution.', 'Epistle', 'Corrects misunderstandings about the timing of the Lord''s return and calls for patient endurance.', 'In-house, public-domain references', ''),
  ('1ti', 54, 'NT', '1 Timothy', 'Paul (disputed)', 'Attributed to Paul; the Pastoral Epistles (1–2 Timothy, Titus) are widely considered deutero-Pauline by modern scholars, though a minority defend Pauline authorship.', '~62–100 AD', 62, 100, 'Unknown', 'Pastoral Epistle; authorship significantly debated.', 'Church order, sound doctrine, and leadership qualifications.', 'Epistle', 'Instructions to Timothy on church organization, guarding sound teaching, and the conduct of various groups.', 'In-house, public-domain references', ''),
  ('2ti', 55, 'NT', '2 Timothy', 'Paul (disputed)', 'Attributed to Paul; Pastoral Epistle; most scholars consider it deutero-Pauline, though some hold Pauline authorship.', '~64–100 AD', 64, 100, 'Rome (prison, if authentic)', 'Pastoral Epistle; authorship significantly debated.', 'Final charge to Timothy to guard the gospel and endure hardship.', 'Epistle', 'A personal and urgent letter to Timothy to remain faithful, endure suffering, and continue in sound teaching.', 'In-house, public-domain references', ''),
  ('tit', 56, 'NT', 'Titus', 'Paul (disputed)', 'Attributed to Paul; Pastoral Epistle; widely considered deutero-Pauline; authorship debated.', '~62–100 AD', 62, 100, 'Crete / Unknown', 'Pastoral Epistle; authorship significantly debated.', 'Church leadership and godly living as the fruit of sound doctrine.', 'Epistle', 'Instructions to Titus on appointing elders in Crete and maintaining good works rooted in grace.', 'In-house, public-domain references', ''),
  ('phm', 57, 'NT', 'Philemon', 'Paul', 'Attributed to Paul; widely accepted as authentic; a personal letter written from prison ~60–62 AD.', '~60–62 AD', 60, 62, 'Rome or Ephesus (prison)', 'Pauline epistle; shortest of Paul''s letters.', 'Intercession for a runaway slave; the new social reality in Christ.', 'Epistle / Letter', 'Paul''s appeal to Philemon to receive his runaway slave Onesimus as a brother in Christ.', 'In-house, public-domain references', ''),
  ('heb', 58, 'NT', 'Hebrews', 'Unknown', 'Author unknown; attributed variously to Paul, Apollos, Priscilla, Barnabas; dated ~60–90 AD; probably pre-70 AD given no mention of the temple''s fall.', '~60–90 AD', 60, 90, 'Unknown', 'Anonymous; authorship a longstanding puzzle.', 'Jesus as the superior high priest and the new covenant''s fulfillment of Levitical ritual.', 'Epistle / Homily', 'A sustained argument that Christ surpasses angels, Moses, and the Levitical priesthood, anchored by the "hall of faith."', 'In-house, public-domain references', ''),
  ('jas', 59, 'NT', 'James', 'James (traditional)', 'Traditionally attributed to James the brother of Jesus; some scholars consider it pseudonymous; date ~45–90 AD.', '~45–90 AD', 45, 90, 'Jerusalem (likely)', 'Catholic/General Epistle; authorship and date debated.', 'Practical faith that produces works, ethical speech, and care for the poor.', 'Epistle / Wisdom', 'A wisdom-rich letter insisting that genuine faith demonstrates itself in works, patience, and prayer.', 'In-house, public-domain references', ''),
  ('1pe', 60, 'NT', '1 Peter', 'Peter (traditional)', 'Attributed to Peter the apostle; some scholars consider it pseudonymous due to the polished Greek; dated ~60–90 AD.', '~60–90 AD', 60, 90, 'Rome ("Babylon")', 'Catholic/General Epistle; authorship debated.', 'Hope in suffering; Christian identity as a holy nation and royal priesthood in a hostile world.', 'Epistle', 'A letter to persecuted Christians urging hope and holy living grounded in Christ''s suffering and resurrection.', 'In-house, public-domain references', ''),
  ('2pe', 61, 'NT', '2 Peter', 'Peter (disputed)', 'Attributed to Peter; most scholars consider it the latest and most disputed NT letter; probably pseudonymous (~100–130 AD).', '~65–130 AD', 65, 130, 'Unknown', 'Catholic/General Epistle; authorship significantly debated.', 'Warning against false teachers; the certainty of the Lord''s return.', 'Epistle', 'Warnings against false teachers who deny the Second Coming, and the call to grow in knowledge and godliness.', 'In-house, public-domain references', ''),
  ('1jn', 62, 'NT', '1 John', 'John (traditional)', 'Attributed to John the apostle (or the "Elder John"); related to the Johannine community; dated ~90–110 AD.', '~90–110 AD', 90, 110, 'Ephesus (likely)', 'Johannine Epistle; closely related to the Gospel of John.', 'Assurance of salvation; the test of love, obedience, and true doctrine.', 'Epistle', 'A letter testing authentic faith by love for one another and confession that Jesus Christ has come in the flesh.', 'In-house, public-domain references', ''),
  ('2jn', 63, 'NT', '2 John', 'John (the Elder)', 'Written by "the Elder"; traditionally identified with John the apostle; part of the Johannine tradition.', '~90–110 AD', 90, 110, 'Unknown', 'Johannine Epistle; shortest NT book.', 'Walk in love and truth; guard against false teachers who deny the Incarnation.', 'Epistle', 'A brief letter warning a "chosen lady" (perhaps a congregation) against welcoming teachers who deny Christ''s humanity.', 'In-house, public-domain references', ''),
  ('3jn', 64, 'NT', '3 John', 'John (the Elder)', 'Written by "the Elder"; traditionally identified with John the apostle; part of the Johannine tradition.', '~90–110 AD', 90, 110, 'Unknown', 'Johannine Epistle.', 'Hospitality to traveling missionaries and the danger of controlling church leaders.', 'Epistle', 'A personal letter commending Gaius for his hospitality and warning against the domineering Diotrephes.', 'In-house, public-domain references', ''),
  ('jud', 65, 'NT', 'Jude', 'Jude (traditional)', 'Attributed to Jude the brother of Jesus; authorship and date debated (50–100 AD range).', '~50–100 AD', 50, 100, 'Unknown', 'Catholic/General Epistle; authorship debated.', 'Defense of the faith against immoral false teachers who have infiltrated the community.', 'Epistle', 'An urgent letter calling believers to "contend for the faith" against infiltrating false teachers.', 'In-house, public-domain references', ''),
  ('rev', 66, 'NT', 'Revelation', 'John of Patmos', 'The author identifies himself as John; traditionally the apostle John; modern scholars often treat the author as a distinct "John of Patmos"; date ~95 AD (Domitian era).', '~95 AD', 95, 95, 'Patmos / Asia Minor', 'Apocalyptic; written under Roman imperial context, likely Domitianic persecution.', 'Symbolic resistance literature for persecuted churches in Asia Minor.', 'Apocalyptic / Prophecy', 'Visions of cosmic conflict between God and evil, the judgment of Rome, and the new creation where God dwells with humanity.', 'In-house, public-domain references', '');
